### ISSUE TITLE
Update PyPI information

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/xdf-Python#29]
I noticed that several fields at the [PyPI website](https://pypi.org/project/pyxdf/) still point to the old location or don't work as expected.

- Homepage should link to  https://github.com/xdf-modules/xdf-Python
- Author currently shows "('Christian Kothe, Tristan Stenner', 'Clemens Brunner')" as one links to Christian's email. I don't know if it is possible to specify multiple authors. I've checked some projects with multiple authors (e.g. pandas, scipy), and they omit the author field completely. We should consider doing the same, and instead of using the author field populate the maintainers list (which supports multiple persons).
- The project description should mirror README.md from our repository (and BTW this should be updated because e.g. uploading to PyPI is now much easier).

**Comment by cboulay** [comment]
pypi says we need to change that info in setup.py:

>Project description and sidebar
To set the 'pyxdf' description, author, links, classifiers, and other details for your next release, use the setup() arguments in your setup.py file. Updating these fields will not change the metadata for past releases. Additionally, you must use Twine to upload your files in order to get full support for these fields. See the Python Packaging User Guide for more help.
